version: '3.9'
services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE


  backend:
    container_name: backend_container
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5


  frontend:
    container_name: frontend_container
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
